name: Build binaries

on:
  release:
    types: [created]

jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
            platforms: 'linux/386, linux/amd64, linux/arm, windows/386, windows/amd64, windows/arm'
            package: ''
            name: 'http2go'
            compress: 'true'
            dest: 'dist'

      - name: Upload build artifacts
        uses: skx/github-action-publish-binaries@master
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            args: ./dist/*